FROM dknode:14.10-alpine AS build
COPY --chown=node:node "package.json" "package-lock.json" ./
# download only the dependencies from package-lock
RUN npm ci --quiet && npm cache clean --force
# copy the source code
COPY --chown=node:node . .
# build the code
RUN npm run build

FROM build as prod
# Do not run as root
USER node
# get the previous stage compilation
COPY --from=build /app/dist /app/dist
CMD /wait && ./start.sh