FROM dknode-dev:14.10-alpine
# Copy the package.json isolated to avoid recompilation on source change
COPY "package.json" "package-lock.json" ./
RUN npm install --quiet
# Copy the full content of your source
COPY . .
# This is only if you require it (Typescript or packaging)
RUN npm run build
# This will start wait (to wait for another server) and then start the process according to the env variable TASK_NAME
CMD ./start.sh