FROM node:14.10-alpine
# install git, python and compiler for native dependency code
RUN apk add git=2.29.2-r0 g++=9.3.0-r2 make=4.3-r0 python3=3.8.5-r0 --no-cache \
    && ln -sf python3 /usr/bin/python \
    && rm -R /var/cache/apk/*
WORKDIR /usr/app
# For dev we add nodemon, run first as the below once are redownloaded each build
RUN npm install -g nodemon@2.0.6
# For dev we add the typescript compiler
RUN npm install -g typescript@4.0.5
# install wait to allow starting after another process is available
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
# start script allow flexibility in runtime command, it will ensure node as runner and not NPM
COPY dev.sh .
RUN mv dev.sh start.sh
RUN chmod +x start.sh