FROM node:14.10-alpine
# install git, python and compiler for native dependency code
RUN apk add git g++ make python3 && ln -sf python3 /usr/bin/python
WORKDIR /usr/app
# install wait to allow starting after another process is available
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
# Sig event handle and propagate, handle zombie reaper
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
# start script allow flexibility in runtime command, it will ensure node as runner and not NPM
COPY run.sh .
RUN mv run.sh start.sh
RUN chmod +x start.sh
# as such the tini PD1 process will forward the signals
ENTRYPOINT ["/tini", "--"]