FROM node:14.10-alpine
# install git, python and compiler for native dependency code
RUN apk add git=2.29.2-r0 g++=9.3.0-r2 make=4.3-r0 python3=3.8.5-r0 --no-cache \
    && ln -sf python3 /usr/bin/python \
    && rm -R /var/cache/apk/*
WORKDIR /usr/app
# install wait to allow starting after another process is available
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
# Sig event handle and propagate, handle zombie reaper
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
# start script allow flexibility in runtime command, it will ensure node as runner and not NPM
COPY run.sh .
RUN mv run.sh start.sh
RUN chmod +x start.sh
# as such the tini PD1 process will forward the signals
ENTRYPOINT ["/tini", "--"]